### ISSUE TITLE
pixeldrain links are failling to download

### ISSUE THREAD

**Issue by nocoel** [Jules-WinnfieldX/CyberDropDownloader#132]
pixeldrain links are failling to download with this error showin in the downloader.log file
`2022-05-08 15:08:11,803:DEBUG:downloaders:downloaders.py:209:We ran into a 400 level error: 404`

**Comment by Jules-WinnfieldX** [comment]
Pixeldrain has been a blemish on the program based on how I implemented it haha, it's due for a rewrite to use their API instead of just URL manipulation. Not surprised it broke. I'll work on it later.

**Comment by nocoel** [comment]
oh i see! thanks for the heads up!

**Comment by Jules-WinnfieldX** [comment]
Just released 2.19.1 which fixes this.

**Comment by nocoel** [comment]
sorry but it appears pixeldrain is still broken, or it broke again, i didn't try it since the fix

**Comment by Jules-WinnfieldX** [comment]
Can I see your downloader.log after you try?

**Comment by nocoel** [comment]
sorry forgot about this! i was wrong it's working
